### ISSUE TITLE
Future чтобы повторная шифровка файла не дешифровала файл

### ISSUE THREAD

**Issue by goblintb** [kruchkov-alexandr/yaml-encrypter-decrypter#3]
Режимы запуска только для шифровки и только для дешифровки, а не чтобы он сам определял что делать

Например новый флаг -crypt
1. вызов yed.exe -crypt dev.yaml 
файл шифруется
2. вызов yed.exe -crypt dev.yaml
с файлом ничего не происходит

Нужно чтобы была возможность проигнорировать ранее зашифрованный файл, а он не шёл на дешифровку

**Comment by kruchkov-alexandr** [comment]
fixed in 0.1.0
